version: "3"
services:
  mysql8:
    container_name: ddd-archetype-go-mysql
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
  redis:
    container_name: ddd-archetype-go-redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
